### PR TITLE
Add modified reinhard support

### PR DESCRIPTION
**Pull request by andreped**
This PR extends Reinhard and adds a new method argument, which enables the user to choose between traditional Reinhard and the Modified version. All backends supported.

**This PR can be merged after** https://github.com/EIDOSLAB/torchstain/pull/27 **, as this branch was based on that branch.**

### CODE REVIEW

**Comment by carloalbertobarbano** [comment]
Hi, I am finally back from vacation. I am merging all the pending PR, however I see some tests are failing due to `FAILED tests/test_tf.py::test_macenko_tf - AttributeError: module 'numpy' has no attribute 'float'` ..we are using np.float in conversions, which was removed starting from numpy 1.24.0. Should we provide a fix?

**Comment by carloalbertobarbano** [comment]
For Modified Reinhard, nice work. I was thinking maybe of refactoring it using a sublcass ModifiedReinhard rather than the `method` argument, in order to keep consistency; but it's not stricly mandatory for now. What do you think?

**Comment by andreped** [comment]
> Should we provide a fix?

Definitely. I just did not observe that on my local testing setup, as I was using an older numpy version. Using `np.float32` should also be backward compatible. Seems like you are making the necessary changes now in your own development branch?

> For Modified Reinhard, nice work. I was thinking maybe of refactoring it using a sublcass ModifiedReinhardNormalizer rather than the `method` argument, in order to keep consistency; but it's not strictly mandatory for now. What do you think?

That was actually my first suggestion, but then I realized how extremely similar the two variants were, and I thought having a method flag makes more sense. But up to you :]

**Comment by carloalbertobarbano** [comment]
Okay, let's keep the method argument for now. Yes, I will merge everything onto the development branch and then I will fix the numpy tests

**Pull request merged**
