### PR TITLE
Tensorflow backend support

### PR DESCRIPTION
**Pull request by andreped**
I accidentally implemented support for TensorFlow backend.

**Changes:**

- Added TensorFlow alternative with equivalent classes and functions which seem to work just fine
- Added TF example in examples.py, along with runtime results for all three
- Minor refactoring of the logic for the backend selection
- ** Removed unecessary inheritance from the HENormalizer class
- *** Added least squares tensorflow implementation relevant to solve a singular matrix problem (which torch did by default).

** Up to you if you find that relevant, if yes, it would be of interest to know why.
*** Could be made more generic, but it is not necessary for this to work.

### CODE REVIEW

**Comment by andreped** [comment]
There might be some potential conflicts between torch and tensorflow when installing. 

I haven't had time to explore and verify this myself, but I have a hunch.

Perhaps some of the devs might have the time, @carloalbertobarbano?

**Comment by carloalbertobarbano** [comment]
Hi André, thanks a lot again for your contribution. Everything seems ok, and I will accept it. 

I would only leave the inheritance from the HENormalizer class. It's a design choice rather than an actual need (e.g. you can use typing hints such as ```normalizer: HENormalizer```)

I will look into the potential installation issues

**Comment by andreped** [comment]
I added back the HENormalizer class inheritance to both the torch and tf normalization classes.

Have you gotten any results from testing installs with both TF and Torch?

**Comment by carloalbertobarbano** [comment]
Thanks a lot. 
I still haven't tried installing the new version. I was thinking maybe to remove both the torch and the tf requirements, and let the user choose which one to install in order to minimize unnecessary dependencies.

**Comment by andreped** [comment]
I also like giving the user the option to choose which backend to use when installing, as it avoids bloatware. However, I would think that if the user wishes to use e.g. the tensorflow backend, it should be defined when pip installing with an argument (or similar). This is quite easy to do. You just need to set this up with the setup.py file, to support said argument, and modify the requirements to be installed there.

One shouldn't force the user to manually having to install TF or Torch, before installing torchstain. Thats annoying. You agree?

Anyway, when this is done, I think it is time for a new release :)

**Comment by carloalbertobarbano** [comment]
Yes, i think this could be the best solution. I will work on it as soon as possible, thanks :+1:

**Pull request merged**
