### PR TITLE
Speed optimizations

### PR DESCRIPTION
**Pull request by ajinkya-kulkarni**
Using slicing and indexing to extract the L, a, and b channels from the input array, and perform the necessary operations using broadcasting.  This allows eliminating the need for explicit loops, improving the performance of the function.

### CODE REVIEW

**Comment by carloalbertobarbano** [comment]
Hi, thanks for your contribution. I updated the workflow in the main branch (they were using a deprecated version of ubuntu). Can you update your branches with the correct worflows so that I can run the unit tests?

**Comment by andreped** [comment]
@carloalbertobarbano this PR now runs CIs with `ubuntu-20.04`. Can you approve the workflow to be run, such that we can test that everything is in order? If yes, we can add the same fix to the two remaining PRs @ajinkya-kulkarni made.

**Comment by andreped** [comment]
I had forgotten to use `ubuntu-20.04` for a pytorch test. However, I have done that now. Also applied the same fixes to all three PRs @ajinkya-kulkarni made. However, just waiting for my PRs to his fork to be merged. If so, then I believe tests could be ran.

**Comment by ajinkya-kulkarni** [comment]
I have synced my fork! Sorry for the delay.

**Comment by andreped** [comment]
> I have synced my fork! Sorry for the delay.

No worries. You have to sync the individual branches as well, not just the main branch. Thats what my PRs to your fork do.

**Comment by carloalbertobarbano** [comment]
All checks passed. Merging into development

**Pull request merged**
